options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE: "sample-api"

availableSecrets:
  secretManager:
    - versionName: projects/340263268846/secrets/nvd-api-key/versions/latest
      env: NVD_API_KEY

steps:
  - name: "maven:3.9-eclipse-temurin-17"
    id: "unit-test"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        mvn -B clean test

  - name: "returntocorp/semgrep:1.66.0"
    id: "sast"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        semgrep --config=p/java --severity=ERROR . || true

  - name: "owasp/dependency-check:latest"
    id: "sca"
    entrypoint: "sh"
    secretEnv:
      - NVD_API_KEY
    args:
      - "-c"
      - |
        mkdir -p /tmp/reports/dependency-check
        /usr/share/dependency-check/bin/dependency-check.sh \
          --scan /workspace \
          --format JSON \
          --out /tmp/reports/dependency-check \
          --nvdApiKey "$$NVD_API_KEY"

  - name: "zricethezav/gitleaks:v8.18.4"
    id: "secret-scan"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        gitleaks detect --source . --no-git --verbose

  - name: "openpolicyagent/conftest:v0.46.0"
    id: "k8s-policy"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        conftest test k8s --policy policies/conftest

artifacts:
  objects:
    location: "gs://${PROJECT_ID}-cicd-reports/${BUILD_ID}/pr"
    paths:
      - "/tmp/reports/**"