
apiVersion: v1
kind: Service
metadata:
  name: sample-api-preview
  labels:
    app: sample-api
spec:
  type: ClusterIP
  selector:
    app: sample-api
    color: green
  ports:
    - name: http
      port: 80
      targetPort: 8080
